apiVersion: monitoring.googleapis.com/v1
kind: ClusterPodMonitoring
metadata:
  name: demoapp-pod-monitoring
spec:
  selector:
    matchLabels:
      app: demo-app
  endpoints:
  - port: 8080
    path: /prometheus
    interval: 30s

